#!/bin/bash
# Frontend deployment script
# Fetches configuration from CloudFormation, builds, and deploys to S3/CloudFront

set -e

# Configuration
ENVIRONMENT="${ENVIRONMENT:-dev}"
REGION="${AWS_REGION:-us-east-1}"
STACK_NAME="kernelworx-ue1-${ENVIRONMENT}"

echo "🚀 Deploying Frontend"
echo "   Environment: ${ENVIRONMENT}"
echo "   Stack: ${STACK_NAME}"
echo "   Region: ${REGION}"
echo ""

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ============================================================
# Step 1: Fetch configuration from CloudFormation
# ============================================================
echo "📡 Fetching configuration from CloudFormation..."

# Get Cognito User Pool ID
USER_POOL_ID=$(aws cloudformation list-stack-resources \
    --stack-name "$STACK_NAME" \
    --query "StackResourceSummaries[?LogicalResourceId=='UserPool6BA7E5F2'].PhysicalResourceId" \
    --output text \
    --region "$REGION")

if [ -z "$USER_POOL_ID" ] || [ "$USER_POOL_ID" == "None" ]; then
    echo "❌ Error: Could not find Cognito User Pool in stack $STACK_NAME"
    exit 1
fi
echo "   User Pool ID: $USER_POOL_ID"

# Get Cognito App Client ID
CLIENT_ID=$(aws cloudformation list-stack-resources \
    --stack-name "$STACK_NAME" \
    --query "StackResourceSummaries[?LogicalResourceId=='UserPoolAppClientDD0407EC'].PhysicalResourceId" \
    --output text \
    --region "$REGION")

if [ -z "$CLIENT_ID" ] || [ "$CLIENT_ID" == "None" ]; then
    echo "❌ Error: Could not find Cognito App Client in stack $STACK_NAME"
    exit 1
fi
echo "   Client ID: $CLIENT_ID"

# Get Cognito Domain
COGNITO_DOMAIN=$(aws cloudformation list-stack-resources \
    --stack-name "$STACK_NAME" \
    --query "StackResourceSummaries[?LogicalResourceId=='UserPoolUserPoolDomain9F01E991'].PhysicalResourceId" \
    --output text \
    --region "$REGION" 2>/dev/null || echo "")

if [ -z "$COGNITO_DOMAIN" ] || [ "$COGNITO_DOMAIN" == "None" ]; then
    # Fallback to constructed domain
    if [ "$ENVIRONMENT" == "prod" ]; then
        COGNITO_DOMAIN="login.kernelworx.app"
    else
        COGNITO_DOMAIN="login.${ENVIRONMENT}.kernelworx.app"
    fi
fi
echo "   Cognito Domain: $COGNITO_DOMAIN"

# Get S3 bucket for static assets
S3_BUCKET=$(aws cloudformation list-stack-resources \
    --stack-name "$STACK_NAME" \
    --query "StackResourceSummaries[?LogicalResourceId=='StaticAssetsDDEE9873'].PhysicalResourceId" \
    --output text \
    --region "$REGION")

if [ -z "$S3_BUCKET" ] || [ "$S3_BUCKET" == "None" ]; then
    echo "❌ Error: Could not find S3 bucket in stack $STACK_NAME"
    exit 1
fi
echo "   S3 Bucket: $S3_BUCKET"

# Get CloudFront Distribution ID
CF_DISTRIBUTION=$(aws cloudformation list-stack-resources \
    --stack-name "$STACK_NAME" \
    --query "StackResourceSummaries[?ResourceType=='AWS::CloudFront::Distribution'].PhysicalResourceId" \
    --output text \
    --region "$REGION")

if [ -z "$CF_DISTRIBUTION" ] || [ "$CF_DISTRIBUTION" == "None" ]; then
    echo "❌ Error: Could not find CloudFront distribution in stack $STACK_NAME"
    exit 1
fi
echo "   CloudFront Distribution: $CF_DISTRIBUTION"

# Construct site domain and API endpoint
if [ "$ENVIRONMENT" == "prod" ]; then
    SITE_DOMAIN="kernelworx.app"
else
    SITE_DOMAIN="${ENVIRONMENT}.kernelworx.app"
fi
API_ENDPOINT="https://api.${SITE_DOMAIN}/graphql"
echo "   Site Domain: $SITE_DOMAIN"
echo "   API Endpoint: $API_ENDPOINT"

# ============================================================
# Step 2: Generate .env.production file (used by Vite for builds)
# ============================================================
echo ""
echo "📝 Generating .env.production file..."

cat > .env.production << EOF
# Auto-generated by deploy.sh - $(date)
# AppSync GraphQL API
VITE_APPSYNC_ENDPOINT=${API_ENDPOINT}
VITE_APPSYNC_REGION=${REGION}

# Cognito User Pool
VITE_COGNITO_USER_POOL_ID=${USER_POOL_ID}
VITE_COGNITO_USER_POOL_CLIENT_ID=${CLIENT_ID}
VITE_COGNITO_DOMAIN=${COGNITO_DOMAIN}

# OAuth Configuration
VITE_OAUTH_REDIRECT_SIGNIN=https://${SITE_DOMAIN}
VITE_OAUTH_REDIRECT_SIGNOUT=https://${SITE_DOMAIN}
EOF

# Also update .env for local dev consistency
cp .env.production .env

echo "   .env.production file updated"

# ============================================================
# Step 3: Build frontend
# ============================================================
echo ""
echo "🔨 Building frontend..."
npm run build

# ============================================================
# Step 4: Sync to S3
# ============================================================
echo ""
echo "☁️  Uploading to S3..."
aws s3 sync dist "s3://${S3_BUCKET}" --delete --region "$REGION"

# ============================================================
# Step 5: Invalidate CloudFront cache
# ============================================================
echo ""
echo "🔄 Invalidating CloudFront cache..."
INVALIDATION_ID=$(aws cloudfront create-invalidation \
    --distribution-id "$CF_DISTRIBUTION" \
    --paths "/*" \
    --query "Invalidation.Id" \
    --output text)

echo "   Invalidation ID: $INVALIDATION_ID"

# ============================================================
# Done!
# ============================================================
echo ""
echo "✅ Deployment complete!"
echo ""
echo "   Site URL: https://${SITE_DOMAIN}"
echo "   CloudFront invalidation may take 1-2 minutes to complete."
echo ""
